Interface for sending SMS to the data collector
cbs-reporting-senegal/cbs pull request #11
Opened 2019-04-13 11:13 UTC by cathinkaw

**Interface for sending SMS to the data collector**

```
    Summary of the changes
    - filtering data collectors
    - A box for the text to be sent to the filtered data collectors 
    - a button to send the manually entered text to the data collectors selected by SMS
    Fixes #339
```

2019-04-13 11:20 UTC, cathinkaw reviewed
Great work, @VihoSerge ! I made a new pull request in our own fork as we are having some issued with how we should do the pull requests into the IRFCGo-fork (as there are many other changes coming with).

Se 3 small comments. If you don't move the styling to sms-send.scss that file should be deleted :)

2019-04-13 11:20 UTC, cathinkaw commented on Source/Reporting/Web/src/app/Management/DataCollectors/send-sms/send-sms.ts
> +  m
what is the m?

2019-04-13 11:20 UTC, cathinkaw commented on Source/Reporting/Web/src/app/Management/DataCollectors/send-sms/send-sms.ts
> +    this.queryCoordinator.execute(new AllDataCollectors())
Great that you have just solved the lack of backend with some console logs.

2019-04-13 11:20 UTC, cathinkaw commented on Source/Reporting/Web/src/styles.scss
> +
Remove one of the new lines

2019-04-13 11:20 UTC, cathinkaw commented on Source/Reporting/Web/src/app/Management/DataCollectors/send-sms/send-sms.html
> +            <label style="color: #333;min-width: 150px;">{{item.fullName +' ' + item.phoneNumbers}}</label>
We sholdn't have styling inline. Maybe you can move it to the send-sms.scss file?

2019-04-13 11:21 UTC, cathinkaw commented on Source/Reporting/Web/src/app/Management/DataCollectors/send-sms/send-sms.html
> +            <label style="color: #333;min-width: 150px;">{{item.fullName +' ' + item.phoneNumbers}}</label>
There is also some inline styling on the label that is a bit higher in the file.

2019-04-13 12:17 UTC, cathinkaw reviewed
Great! I will wait to merge it because we don't have the backend support yet. But great work @VihoSerge  :D

2019-04-14 12:13 UTC, woksin commented
I merged it with master and fixed an error that I couldn't run the frontend because of a version mismatch. However this SMS interface does not work fully as intended I guess, that may be because I merged with master.

@VihoSerge @cathinkaw

2019-04-23 07:18 UTC, woksin requested changes
Merge with master and make it functional

2023-09-28 06:32 UTC, closed without merging